version: "3.3"
services:
  ton-node:
    image: mytonctrl:2
    container_name: mytonctrl-archive-node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
        MYTONCTRL_VERSION: ${MYTONCTRL_VERSION}
        TELEMETRY: ${TELEMETRY}
        IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
        MODE: ${MODE}
    restart: always
    tty: true
    volumes:
      - ton:/var/ton-work
      - mytoncore:/usr/local/bin/mytoncore
    network_mode: host
    environment:
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
      IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
      DUMP: ${DUMP}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '16'  # 添加 CPU 使用限制
          memory: 32g  # 添加内存限制
volumes:
  ton:
  mytoncore:
