version: "3.3"
services:
  ton-node:
    image: mytonctrl:2
    container_name: mytonctrl-archive-node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
        MYTONCTRL_VERSION: ${MYTONCTRL_VERSION}
        TELEMETRY: ${TELEMETRY}
        IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
        MODE: ${MODE}
    restart: always
    tty: true
    volumes:
      - ton-work:/var/ton-work
      - mytoncore:/usr/local/bin/mytoncore
    network_mode: host
    ports:
      - "8888:8888"  # 映射外部端口 8888 到容器端口 8888
      - "9999:9999"  # 映射外部端口 9999 到容器端口 9999
    environment:
      GLOBAL_CONFIG_URL: ${GLOBAL_CONFIG_URL}
      IGNORE_MINIMAL_REQS: ${IGNORE_MINIMAL_REQS}
      DUMP: ${DUMP}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
volumes:
  ton-work:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mytonctrl-archive-node/ton-work
  mytoncore:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mytonctrl-archive-node/mytoncore